# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
gui:
  theme:
    lightTheme: true
    selectedLineBgColor:
      - cyan

os:
  open: 'open {{filename}}'
  edit: 'nvim'
  Edit,EditAtLine: '{{editor}} +{{line}} {{filename}}'
